version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app1
    container_name: laravel_app1
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3308:3306"

  webserver:
    image: nginx:alpine
    container_name: laravel_web1
    restart: unless-stopped
    ports:
      - "8000:80" 
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: